### ISSUE TITLE
Icons doesn't render on searchpage

### ISSUE THREAD

**Issue by ribaltazar** [maynhile13105/CSE110-Project-TritonCook#19]
When searchpage is loaded by typing (localhost/home/search), icons doesnt load/.

![image](https://github.com/user-attachments/assets/e356d53f-e84c-4741-abfa-ee4418f6fca6)

but it loads when clicked through the navigation bar.

![image](https://github.com/user-attachments/assets/47d6b0c5-095d-4482-ad0f-3d7494b26bc2)

**Comment by yifanzhu1121** [comment]
part of the related bug for "the search bar icon not shown while all the other icons shown" is fixed, caused by missing the first backslash in the file path /images/filename.svg; now in the second pic all the icons should be shown correctly

waiting to check the issue for the first pic

**Comment by ribaltazar** [comment]
fixed. forgot backlash in front of svg path
